---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update -y && sudo apt-get install -y inkscape
      - run: mkdir target
      - run: inkscape --export-png=target/zarr-gradient.png zarr-gradient.svg
      - env:
          FILES: zarr-pink-horizontal zarr-pink-stacked
        run: |
          for file in $FILES; do
            inkscape --export-background-opacity=0 --export-png=target/${file}-transparent.png ${file}.svg
            inkscape --export-background="#ffffff" --export-png=target/${file}-white.png ${file}.svg
            inkscape --export-background="#000000" --export-png=target/${file}-black.png ${file}.svg
          done
          zip -r logos.zip target/
      - name: Upload artwork as artifact
        uses: actions/upload-artifact@v2
        with:
          name: logos.zip
          path: logos.zip

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download artwork artifact
        uses: actions/download-artifact@v2
        with:
          name: logos.zip
          path: .
      - run: unzip logos.zip
      - name: Upload website as release asset
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" target/*.png
