---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: brew install https://github.com/Homebrew/homebrew-core/raw/46a2ef7c9f0380b8e19f8dfe37270caa27581353/Formula/imagemagick.rb --with-librsvg
      - run: mkdir target
      - run: convert zarr-gradient.svg target/zarr-gradient.png
      - env:
          FILES: zarr-pink-horizontal zarr-pink-stacked
        run: |
          for file in $FILES; do
            convert -background none ${file}.svg target/${file}-transparent.png
            convert -background white ${file}.svg target/${file}-on-white.png
            convert -background black ${file}.svg target/${file}-on-black.png
          done
          zip -r logos.zip target/
      - name: Upload artwork as artifact
        uses: actions/upload-artifact@v2
        with:
          name: logos.zip
          path: logos.zip

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download artwork artifact
        uses: actions/download-artifact@v2
        with:
          name: logos.zip
          path: .
      - run: unzip logos.zip
      - name: Upload website as release asset
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" target/*.png
