---
name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: brew install imagemagick
      - run: mkdir target
      - run: convert zarr-gradient.svg target/zarr-gradient.png
      - env:
          FILES: zarr-pink-horizontal zarr-pink-stacked
        run: |
          for file in $FILES; do
            convert -background none ${file}.svg target/${file}-transparent.png
            convert -background white ${file}.svg target/${file}-on-white.png
            convert -background black ${file}.svg target/${file}-on-black.png
          done
      - name: Upload artwork as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: target/*.png

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artwork artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: target/*.png
      - name: Upload website as release asset
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          tagname="${GITHUB_REF#refs/tags/}"
          gh release create "$tagname" target/*.png
